name: 🧪 Validar HTML y CSS (W3C)

on:
  push:
    branches: [main]
    paths:
      - '**.html'
      - '**.css'
  pull_request:
    paths:
      - '**.html'
      - '**.css'

jobs:
  w3c-validation:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🧪 Validar HTML y CSS con html5validator
        uses: Cyb3r-Jak3/html5validator-action@v2
        with:
          root: .       # Carpeta raíz donde están los archivos
          log_level: INFO
